on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: docker
        run: |
          set -x
          id -a
          sudo bash -c 'cat << EOF > /etc/docker/daemon.json
          { "userns-remap": "default" }
          EOF'
          sudo systemctl restart docker
          sudo cat /etc/docker/daemon.json
          cat /etc/subuid
          cat /etc/subgid
          docker run -h ipa.example.test --sysctl net.ipv6.conf.all.disable_ipv6=0 --workdir /github/workspace -v "$HOME/ipa-data":"/da/data":Z -v "${{ github.workspace }}":"/github/workspace" -v "$HOME/.m2":"/root/.m2" freeipa/freeipa-server:rocky-9 ipa-server-install --unattended --realm=EXAMPLE.TEST --ds-password=password --admin-password=password --idstart=60000 --no-ntp

