on:
  push:

jobs:
  test-project:
    name: test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - shell: powershell
        name: Link the cached Maven repository to the OS-dependent location
        if: runner.os == 'Windows'
        run: |
          mkdir -p ../../../.m2/repository
          cmd /c mklink /d $HOME\.m2\repository D:\.m2\repository
      - name: Run tests
        shell: bash
        run: |
          set -x
          mkdir -p ~/.m2/repository/com/github/eirslett
          ./mvnw clean install
