on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: docker
        run: |
          set -x
          id -a
          lsb_release -a
          sudo bash -c 'cat << EOF > /etc/docker/daemon.json
          { "userns-remap": "default" }
          EOF'
          sudo systemctl restart docker
          cat /etc/subuid
          cat /etc/subgid
          mkdir "$HOME/ipa-data"
          docker --version
          docker run --userns=host --tmpfs /run --tmpfs /tmp -h ipa.example.test --sysctl net.ipv6.conf.all.disable_ipv6=0 freeipa/freeipa-server:rocky-9 ipa-server-install --unattended --realm=EXAMPLE.TEST -p lala1234 -a lala1234 --idstart=60000

