on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fake fips
        run: |
          cd .github/fake_fips
          make
          sudo insmod fake_fips.ko
        shell: bash
      - name: Build
        uses: docker://fedora:latest
        with:
          entrypoint: .github/scripts/run-fedora.sh
