on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - id: weekly-cache-key
        name: Key for weekly rotation of cache
        shell: bash
        run: echo "key=mvn-`date -u "+%Y-%U"`" >> $GITHUB_OUTPUT
      - id: cache-maven-repository
        name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ steps.weekly-cache-key.outputs.key }}
      - id: check-maven-cache
        name: Check cache has no Keycloak artifacts
        if: steps.cache-maven-repository.outputs.cache-hit == 'true'
        shell: bash
        run: |
          if ( stat ~/.m2/repository/org/keycloak &>/dev/null ); then
            echo "Found org/keycloak artifacts in Maven repository cache"
            ls ~/.m2/repository/org/keycloak
            exit 1
          fi
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - name: Run tests
        run: |
          echo $JAVA_HOME
