on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fake fips
        run: |
          cd .github/fake_fips
          make
          sudo insmod fake_fips.ko
        shell: bash
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - id: weekly-cache-key
        name: Key for weekly rotation of cache
        shell: bash
        run: echo "key=mvn-`date -u "+%Y-%U"`" >> $GITHUB_OUTPUT
      - id: cache-maven-repository
        name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ steps.weekly-cache-key.outputs.key }}
      - id: check-maven-cache
        name: Check cache has no Keycloak artifacts
        if: steps.cache-maven-repository.outputs.cache-hit == 'true'
        shell: bash
        run: |
          if ( stat ~/.m2/repository/org/keycloak &>/dev/null ); then
            echo "Found org/keycloak artifacts in Maven repository cache"
            ls ~/.m2/repository/org/keycloak
            exit 1
          fi
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - name: Compile
        run: |
          ./mvnw install -DskipTests
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: registry.access.redhat.com/ubi8/ubi:latest
          options: >-
            -v /home/runner/.m2:/root/.m2
            -v /home/runner/work/github-actions/github-actions:/home/runner/work/github-actions/github-actions
          run: |
            cd /home/runner/work/github-actions/github-actions
            dnf install -y java-17-openjdk-devel crypto-policies-scripts
            fips-mode-setup --enable --no-bootcfg
            if fips-mode-setup --is-enabled; then
              JAVA_HOME=/etc/alternatives/java_sdk_17 ./mvnw test -B -fae -pl testsuite
            else
              exit 1
            fi
