on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    container:
      image: freeipa/freeipa-server:fedora-rawhide
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - id: weekly-cache-key
        name: Key for weekly rotation of cache
        shell: bash
        run: echo "key=mvn-`date -u "+%Y-%U"`" >> $GITHUB_OUTPUT
      - id: cache-maven-repository
        name: Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ steps.weekly-cache-key.outputs.key }}
      - id: check-maven-cache
        name: Check cache has no Keycloak artifacts
        if: steps.cache-maven-repository.outputs.cache-hit == 'true'
        shell: bash
        run: |
          if ( stat ~/.m2/repository/org/keycloak &>/dev/null ); then
            echo "Found org/keycloak artifacts in Maven repository cache"
            ls ~/.m2/repository/org/keycloak
            exit 1
          fi
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - name: Tests
        run: |
          id -a
          pwd
          systemctl status ipa-server-upgrade.service

          if ! grep -q ^ldap_user_extra_attrs /etc/sssd/sssd.conf; then
            sed -i '/ldap_tls_cacert/a ldap_user_extra_attrs = mail:mail, sn:sn, givenname:givenname, telephoneNumber:telephoneNumber' /etc/sssd/sssd.conf
          fi
          if ! grep -q ^user_attributes /etc/sssd/sssd.conf; then
            sed -i '/allowed_uids/a user_attributes = +mail, +telephoneNumber, +givenname, +sn' /etc/sssd/sssd.conf
          fi

          systemctl restart sssd
          sss_cache -E

          echo "auth    required   pam_sss.so" >>/etc/pam.d/keycloak
          echo "account required   pam_sss.so" >>/etc/pam.d/keycloak

          printf "%b" "password\n" | kinit admin
          ipa group-add --desc='test group' testgroup
          ipa user-add emily --first=Emily --last=Jones --email=emily@jones.com --random
          ipa group-add-member testgroup --users=emily
          ipa user-add bart --first=bart --last=bart --email= --random
          ipa user-add david --first=david --last=david --random
          kdestroy

          ldapmodify -D "cn=Directory Manager" -w password <<EOF
          dn: uid=emily,cn=users,cn=accounts,dc=example,dc=test
          changetype: modify
          replace: userpassword
          userpassword: emili123

          dn: uid=bart,cn=users,cn=accounts,dc=example,dc=test
          changetype: modify
          replace: userpassword
          userpassword: bart123

          dn: uid=david,cn=users,cn=accounts,dc=example,dc=test
          changetype: modify
          replace: userpassword
          userpassword: david123

          EOF

          printf "%b" "password\n" | kinit admin
          ipa user-disable david
          kdestroy
