on:
  push:

jobs:
  test-project:
    name: test
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install needed packages
        run: dnf install -y java-11-openjdk-devel nss-tools crypto-policies-scripts maven-openjdk11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: mvn -B -fae clean install
